on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  0 */3 * * * # every three hours
name: update
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: graphs - install dependencies
      run: |
        sudo apt-get install -y python3-setuptools 
        pip3 install -r requirements.txt
    - name: graphs - run
      run: python3 ohio-covid19.py 
    - name: schools - run
      run: |
        cd schools
        pip3 install -r requirements.txt
        python3 schools.py
    - name: generate screenshot
      run: |
        cd ../imgs
        sudo apt-get install chromium-chromedriver
        pip3 install -r requirements.txt
        python3 screenshot.py
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'
